### PR TITLE
Added releaser Github action. Chart moved to place expected by releaser.

### PR DESCRIPTION
**Pull request by ksa-real**
https://github.com/manticoresoftware/manticoresearch-helm/issues/1

### CODE REVIEW

**Comment by sanikolaev** [comment]
@djklim87 pls review

**Comment by sanikolaev** [comment]
I know @djklim87 has also almost implemented a similar solution. 

@djklim87 please review this PR and add your changes into it.

**Comment by ksa-real** [comment]
You probably meant the other diff. This one is a single file diff to auto-release the helm chart to Github Pages.

**Comment by sanikolaev** [comment]
> You probably meant the other diff.

No. It's just that this task has been in works too.

**Pull request merged**
